jobs:

- name: singlecluster_noarch_cdh
  plan:
  - aggregate:
    - get: cdh_tars_tarball
    - get: jdbc
    - get: tomcat
    - get: curl
      resource: curl_bin_tarball
    - get: maven_centos6_image
    - get: singlecluster
      trigger: true
  - task: package_singlecluster
    image: maven_centos6_image
    file: singlecluster/package_singlecluster_cdh.yml
  - put: singlecluster-CDH
    params:
      file: artifacts/singlecluster-CDH.tar.gz

- name: singlecluster_noarch_hdp
  plan:
  - aggregate:
    - get: hdp_tars_tarball
    - get: jdbc
    - get: tomcat
    - get: curl
      resource: curl_bin_tarball
    - get: maven_centos6_image
    - get: singlecluster
      trigger: true
  - task: package_singlecluster
    image: maven_centos6_image
    file: singlecluster/package_singlecluster_hdp.yml
  - put: singlecluster-HDP
    params:
      file: artifacts/singlecluster-HDP.tar.gz

resources:

- name: singlecluster-HDP
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: {{pxf-aws-bucket-name}}
    region_name: {{aws-region}}
    versioned_file: singlecluster-without-pxf/singlecluster-HDP.tar.gz

- name: singlecluster-CDH
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: {{pxf-aws-bucket-name}}
    region_name: {{aws-region}}
    versioned_file: singlecluster-without-pxf/singlecluster-CDH.tar.gz

- name: singlecluster
  type: git
  source:
    uri: https://github.com/l-wang/singlecluster-pipeline.git
    branch: master

# HDP Tars Tarball
- name: hdp_tars_tarball
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: {{pxf-aws-bucket-name}}
    region_name: {{aws-region}}
    versioned_file: hortonworks/HDP-2.5.3.0-centos6-tars-tarball.tar.gz

# CDH Tars Tarball
- name: cdh_tars_tarball
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: {{pxf-aws-bucket-name}}
    region_name: {{aws-region}}
    versioned_file: cloudera/CDH-5.10.2.tar.gz

- name: jdbc
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: {{pxf-aws-bucket-name}}
    region_name: {{aws-region}}
    versioned_file: jdbc/postgresql-jdbc-8.4.704.jar

- name: tomcat
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: {{pxf-aws-bucket-name}}
    region_name: {{aws-region}}
    versioned_file: tomcat/apache-tomcat-7.0.62.tar.gz

- name: curl_bin_tarball
  type: s3
  source:
    access_key_id: {{aws-access-key-id}}
    secret_access_key: {{aws-secret-access-key}}
    bucket: {{aws-bucket-name}}
    region_name: {{aws-region}}
    versioned_file: hdb_dependencies/binaries/curl-7.50.3-bin.tgz

- name: maven_centos6_image
  type: docker-image
  source:
    repository: pivotaldata/maven-centos6
    username: {{docker-username}}
    password: {{docker-password}}
