jobs:

- name: singlecluster_noarch_cdh
  plan:
  - aggregate:
    - get: cdh_tars_tarball
    - get: jdbc
    - get: tomcat
    - get: centos-gpdb-dev-6
    - get: singlecluster
      trigger: true
  - task: package_singlecluster
    image: centos-gpdb-dev-6
    file: singlecluster/package_singlecluster_cdh.yml
  - put: singlecluster-CDH
    params:
      file: artifacts/singlecluster-CDH.tar.gz

- name: singlecluster_noarch_hdp
  plan:
  - aggregate:
    - get: hdp_tars_tarball
    - get: jdbc
    - get: tomcat
    - get: centos-gpdb-dev-6
    - get: singlecluster
      trigger: true
  - task: package_singlecluster
    image: centos-gpdb-dev-6
    file: singlecluster/package_singlecluster_hdp.yml
  - put: singlecluster-HDP
    params:
      file: artifacts/singlecluster-HDP.tar.gz

resources:

- name: singlecluster-HDP
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    bucket: {{pxf-aws-bucket-name}}
    region_name: {{aws-region}}
    versioned_file: singlecluster-without-pxf/singlecluster-HDP.tar.gz

- name: singlecluster-CDH
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    bucket: {{pxf-aws-bucket-name}}
    region_name: {{aws-region}}
    versioned_file: singlecluster-without-pxf/singlecluster-CDH.tar.gz

- name: singlecluster
  type: git
  source:
    uri: https://github.com/Pivotal-DataFabric/singlecluster-pipeline.git
    branch: master

# HDP Tars Tarball
- name: hdp_tars_tarball
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    bucket: {{pxf-aws-bucket-name}}
    region_name: {{aws-region}}
    versioned_file: hortonworks/HDP-2.5.3.0-centos6-tars-tarball.tar.gz

# CDH Tars Tarball
- name: cdh_tars_tarball
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    bucket: {{pxf-aws-bucket-name}}
    region_name: {{aws-region}}
    versioned_file: cloudera/CDH-5.10.2.tar.gz

- name: jdbc
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    bucket: {{pxf-aws-bucket-name}}
    region_name: {{aws-region}}
    versioned_file: jdbc/postgresql-jdbc-8.4.704.jar

- name: tomcat
  type: s3
  source:
    access_key_id: {{bucket-access-key-id}}
    secret_access_key: {{bucket-secret-access-key}}
    bucket: {{pxf-aws-bucket-name}}
    region_name: {{aws-region}}
    versioned_file: tomcat/apache-tomcat-7.0.62.tar.gz

- name: centos-gpdb-dev-6
  type: docker-image
  source:
    repository: pivotaldata/centos-gpdb-dev
    tag: '6-gcc6.2-llvm3.7'
